language: node_js
node_js: "node"

before_script:
  - npm install @qooxdoo/compiler

script:
  - npx qx test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  local-dir: compiled/source
  on:
    branch: master
